# Generated by Django 4.0.1 on 2022-01-18 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='update_description_text',
        ),
    ]
