# Generated by Django 4.0.1 on 2022-01-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_remove_good_update_description_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='update_description_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
